name: PHP Tests

on:
    push:
        branches:
            - "master"
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.1, 8.2, 8.3, 8.4 ]
                dependencies: [ "lowest", "highest" ]

        name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install dependencies with Composer
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: "${{ matrix.dependencies }}"
                    composer-options: "${{ matrix.composer-options }}"

            -   name: Run tests
                run: vendor/bin/phpunit
