name: PHP Tests (PHPUnit 12)

on:
    push:
        branches:
            - "master"
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.3, 8.4 ]
                dependencies: [ "lowest", "highest" ]

        name: PHP ${{ matrix.php }} - ${{ matrix.dependencies }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Set up PHPUnit version
                run: composer require phpunit/phpunit:^12.3 --no-update

            -   name: Install dependencies with Composer
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: Run tests
                run: vendor/bin/phpunit
